### ISSUE TITLE
Request support for libsodium crypto_box_seal and crypto_box_seal_open

### ISSUE THREAD

**Issue by grempe** [crypto-rb/rbnacl#120]
Would it be possible to add support for sealed boxes which were recently added to libsodium in v1.0.3?

https://download.libsodium.org/doc/public-key_cryptography/sealed_boxes.html

Also, in light of this addition, the second wiki entry about mutual authentication now seems too strong. No?

https://github.com/cryptosphere/rbnacl/wiki/Frequently-Asked-Questions

```
Q: Is there any way to decrypt a Crypto::Box message with only a private key without requiring the public key of the sender?

A: No, and there never will be. This is an integral part of how the Curve25519 algorithm operates, and the mutual authentication it provides is a design principle you should consider whenever using public key cryptography.
```

**Comment by tarcieri** [comment]
Yes, we can add both, either wrapping libsodium's version or just implementing it in pure Ruby.

And yes, you're correct, that comment is overblown.

**Comment by namelessjon** [comment]
I suggest we wrap the libsodium version.  We're assured of compatibility, but more importantly, it takes care of zeroing out everything important before ruby has any chance of making memory copies of the secret key involved.

**Comment by namelessjon** [comment]
Relevant to this:  Which version(s) of libsodium are we pulling in via FFI on Travis and/or officially supporting?

**Comment by tarcieri** [comment]
The tests use the `rbnacl-libsodium` gem (sourced from the `:test` block of the Gemfile), which vendors libsodium 1.0.3 (latest version).

As to what the minimum version we support is, I would suggest 1.0.0 at this point.

**Comment by tarcieri** [comment]
Note that a Ruby implementation of the seal/unseal API would allow us to support these APIs on all 1.0.0+ versions of libsodium

**Comment by namelessjon** [comment]
:+1: to saying the minimum support is 1.0.0.  Can you set up a travis case to specifically test we don't break vs 1.0.0?

I had considered a ruby version would let us do that.  I guess the convenience outweighs the small additional risk of secrets in memory, given we're already working in ruby...

**Comment by tarcieri** [comment]
We can use Travis's build matrix's parameterized environment variables to test against both `rbnacl-libsodium` 1.0.0 and whatever the latest is. I can put together a PR to do that.

**Comment by gogocurtis** [comment]
Where is this at? We are thinking of implementing this same thing and found this code.

**Comment by gjtorikian** [comment]
I'd also like to know, and can happily contribute bindings if necessary.

**Comment by tarcieri** [comment]
#168 was fine, but didn't have any tests. I described the tests I'd like to see here: https://github.com/crypto-rb/rbnacl/pull/168#issuecomment-396998628

**Comment by tarcieri** [comment]
Added in #184
