### ISSUE TITLE
Windows: 'Could not open library'

### ISSUE THREAD

**Issue by sapphyrus** [crypto-rb/rbnacl#150]
When I try to load rbnacl I get this error:

![image](https://cloud.githubusercontent.com/assets/22681389/21785284/3c1d4bc8-d6bf-11e6-8760-ed23b8da732d.png)

As you can see from the screenshot the file does exist.

My script:
`::RBNACL_LIBSODIUM_GEM_LIB_PATH = 'C:\sapphyrusxyz\aexyte\Server\libsodium\Win32\Release\v140\dynamic\libsodium.dll'`
`require 'rbnacl'
`

**Comment by Lasertrap00** [comment]
Hello

**Comment by tarcieri** [comment]
I know rather little about Windows. Perhaps you should ask upstream at:

https://github.com/ffi/ffi

**Comment by sapphyrus** [comment]
Alright, I'll do that. Thanks!
