### ISSUE TITLE
argon2i breaks with libsodium 1.0.15

### ISSUE THREAD

**Issue by elijh** [crypto-rb/rbnacl#177]
With libsodium 1.0.13, both argon2i and argon2id digests work fine with rbnacl. However, if you upgrade to libsodium 10.0.15, then argon2id continues to work but argon2i stops working (libsodium returns null digest). 

I am not sure what the problem is but I am putting this here in case someone else hits this problem. I plan to investigate.

**Comment by tarcieri** [comment]
Did RbNaCl 6.0+ address this issue? Several things changed in the Argon2 bindings, including some new bugs (#183)

**Comment by tarcieri** [comment]
Closing as obsolete
