### ISSUE TITLE
will Auth be implemented

### ISSUE THREAD

**Issue by myneid** [crypto-rb/rbnacl#178]
i have a need to verify a message that was encrypted by checking it with their  public key as a third party.
I went down the hole of using auth. i noticed that KEYBYTES and BYTES was 0, which i found odd.
once i tried to change that, i then looked at all the code and realized that this is not implemented.
any plans to do that?
if not any other way you can point em to for doing this?

**Comment by tarcieri** [comment]
Which "auth" are you talking about? NaCl's `crypto_auth` function invokes HMAC, which is available here:

https://github.com/crypto-rb/rbnacl/wiki/One-Time-Authentication

However, from this description:

> i have a need to verify a message that was encrypted by checking it with their public key as a third party.

...it sounds like you want to verify a digital signature, in which case you want Ed25519:

https://github.com/crypto-rb/rbnacl/wiki/Digital-Signatures

**Comment by myneid** [comment]
https://www.rubydoc.info/github/cryptosphere/rbnacl/RbNaCl/Auth

given a ciphertext and a public key i was hoping i could verify that person was the one that created that ciphertext.
but i will go down the route of signing each ciphertext as well.
thanks

**Comment by tarcieri** [comment]
Yeah, that API is the HMAC API, and is symmetric (i.e. verifiers can also create HMACs).

In fact the only thing in NaCl that does not have this property is Ed25519 digital signatures.
