### ISSUE TITLE
stream interface of libsodium

### ISSUE THREAD

**Issue by Eusebius1920** [crypto-rb/rbnacl#192]
Is there a way to use `rbnacl` together with the (relativley) new stream interface of libsodium? Are there any plans to add this?

(Documented here: https://libsodium.gitbook.io/doc/secret-key_cryptography/secretstream)

**Comment by tarcieri** [comment]
I don't personally plan on implementing it. I've implemented Phil Rogaway's STREAM construction as part of Miscreant, which I personally prefer to the bespoke scheme in libsodium:

https://github.com/miscreant/xstream

PRs accepted, though.

**Comment by Eusebius1920** [comment]
Thanks for your feedback. I will see if I can contribute a PR in the next weeks.
