### ISSUE TITLE
Correct way to derive a key from a passphrase

### ISSUE THREAD

**Issue by dkam** [crypto-rb/rbnacl#193]
Is it possible / reasonable to derive a key for SimpleBox from a password / passphrase?  Or do I just need to use a generated random password?

**Comment by tarcieri** [comment]
The password hashing algorithms in this library can all be used for cryptographic key derivation. However, generating a strong password is still probably a good idea to ensure minimum entropy (a cryptographic key derived from a password is still only as strong as the original password):

https://github.com/crypto-rb/rbnacl/wiki/Password-Hashing

**Comment by dkam** [comment]
I've looked at that page and had a go at using it for key derivation, however I understood it to be used for hashing a password so that it can be later verified.   If I run through that example for Argon2 :

```
password = 'password'
salt = RbNaCl::Random.random_bytes(RbNaCl::PasswordHash::Argon2::SALTBYTES)

opslimit = 5
memlimit = 7_256_678

digest_size = 32

digest_1 = RbNaCl::PasswordHash.argon2(
  password, 
  salt,
  opslimit,
  memlimit,
  digest_size
)

salt = RbNaCl::Random.random_bytes(RbNaCl::PasswordHash::Argon2::SALTBYTES)
digest_2 = RbNaCl::PasswordHash.argon2(
  password, 
  salt,
  opslimit,
  memlimit,
  digest_size
)

digest_1 == digest_2
=> false
```

The calculated digests are different - so they can't be used as the key - right?  So how is it supposed to work? Are we supposed to use the same salt each time maybe?

**Comment by tarcieri** [comment]
> The calculated digests are different - so they can't be used as the key - right? So how is it supposed to work? Are we supposed to use the same salt each time maybe?

Yes, you need to record the salt that was used somewhere, and supply the same one if you intend to derive the same cryptographic key.

> I've looked at that page and had a go at using it for key derivation, however I understood it to be used for hashing a password so that it can be later verified

Both scrypt and Argon2 are password-based key derivation functions (KDF), and are explicitly designed for the purpose of generating cryptographic keys from a password. From Wikipedia:

https://en.wikipedia.org/wiki/Key_derivation_function

> KDFs happen to have the characteristics desired for a "password hash function", even though they were not originally designed for this purpose.

**Comment by dkam** [comment]
Awesome - thanks very much.  Is it possible to update the wiki page to include that information for key derivation?
