### ISSUE TITLE
issues with installing chef client from windows machine(win 10)

### ISSUE THREAD

**Issue by bbojjam** [crypto-rb/rbnacl#196]
i'm getting below error while running knife bootstrap command for installing chef client from windows machine. kindly let us know if anyone has solution for it.

PS C:\chef\chef-repo> knife bootstrap 13.127.3.42 --sudo -x ec2-user -N demo-client
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-1.10.0-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib': (LoadError)pen library 'sodium': The specified module could not be found.
.
Could not open library 'sodium.dll': The specified module could not be found.
.
Could not open library 'libsodium.so.18': The specified module could not be found.
.
Could not open library 'libsodium.so.18.dll': The specified module could not be found.
.
Could not open library 'libsodium.so.23': The specified module could not be found.
.
Could not open library 'libsodium.so.23.dll': The specified module could not be found.
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-1.10.0-x64-mingw32/lib/ffi/library.rb:99:in `map'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-1.10.0-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
        from C:/Users/bbojjam/AppData/Local/chefdk/gem/ruby/2.5.0/gems/rbnacl-7.0.0/lib/rbnacl/sodium.rb:11:in `extended'
        from C:/Users/bbojjam/App
Data/Local/chefdk/gem/ruby/2.5.0/gems/rbnacl-7.0.0/lib/rbnacl/sodium/version.rb:14:in `extend'
        from C:/Users/bbojjam/AppData/Local/chefdk/gem/ruby/2.5.0/gems/rbnacl-7.0.0/lib/rbnacl/sodium/version.rb:14:in `<module:Version>'
        from C:/Users/bbojjam/AppData/Local/chefdk/gem/ruby/2.5.0/gems/rbnacl-7.0.0/lib/rbnacl/sodium/version.rb:9:in `<module:Sodium>'
        from C:/Users/bbojjam/AppData/Local/chefdk/gem/ruby/2.5.0/gems/rbnacl-7.0.0/lib/rbnacl/sodium/version.rb:7:in `<module:RbNaCl>'
        from C:/Users/bbojjam/AppData/Local/chefdk/gem/ruby/2.5.0/gems/rbnacl-7.0.0/lib/rbnacl/sodium/version.rb:6:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/Users/bbojjam/AppData/Local/chefdk/gem/ruby/2.5.0/gems/rbnacl-7.0.0/lib/rbnacl.rb:12:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems
/core_ext/kernel_require.rb:130:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/jwt-2.1.0/lib/jwt/signature.rb:11:in `<top (required)>'        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/jwt-2.1.0/lib/jwt.rb:8:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/signet-0.11.0/lib/signet
/oauth_2/client.rb:21:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/googleauth-0.6.7/lib/googleauth/signet.rb:30:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/googleauth-0.6.7/lib/googleauth/compute_engine.rb:31:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/
gems/googleauth-0.6.7/lib/googleauth/application_default.rb:30:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/googleauth-0.6.7/lib/googleauth.rb:30:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:23:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C
:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/generated/google/apis/compute_v1/service.rb:15:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.23.9/generated/google/apis/compute_v1.rb:15:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/knife-google-3.3.7/lib/chef/knife/cloud/google_service.rb:24:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib
/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/knife-google-3.3.7/lib/chef/knife/google_disk_create.rb:22:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:85:in `load'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:85:in `block in load_commands'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:85:in `each'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:85:in `load_commands'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:95:in `load_command'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/g
ems/chef-14.10.9-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:109:in `command_class_from'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife.rb:152:in `subcommand_class_from'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife.rb:215:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/application/knife.rb:161:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/bin/knife:24:in `<top (required)>'
        from C:/opscode/chefdk/modules/chef/../../bin/knife:322:in `load'
        from C:/opscode/chefdk/modules/chef/../../bin/knife:322:in `<main>'

**Comment by tarcieri** [comment]
That looks like libsodium is not (properly) installed.

**Comment by ankane** [comment]
@bbojjam Can you try renaming `libsodium.dll` to `sodium.dll` in `C:\Windows\System32`?

**Comment by tarcieri** [comment]
Looks like the documentation issues behind this were resolved in #198
