### ISSUE TITLE
Update Windows instructions to copy to sodium.dll instead of libsodium.dll

### ISSUE THREAD

**Issue by ankane** [crypto-rb/rbnacl#198]
The current [Windows instructions](https://github.com/crypto-rb/rbnacl/wiki/Installing-libsodium#windows) have you copy `libsodium.dll` into `System32`. However, `ffi_lib` looks for `sodium.dll`, not `libsodium.dll` ([Ruby-FFI code](https://github.com/ffi/ffi/blob/d9e07ce7085ca12d0b54d78f15c05f2e64630247/lib/ffi/platform.rb#L107) - doesn't add `lib` prefix on Windows).

![Screen Shot 2019-07-03 at 1 39 52 AM](https://user-images.githubusercontent.com/220358/60566106-d5f4e480-9d33-11e9-8170-91e0d064db2a.png)

Should fix #196

**Comment by ankane** [comment]
Could also do something [like this](https://github.com/ankane/rbnacl/commit/77799442fe4e6afa766be3f0420232d6fbf3e2b7) if `libsodium.dll` is the preferred name for the file.

**Comment by tarcieri** [comment]
@ankane I've temporarily disabled restricted access to the Wiki if you would like to update the Windows instructions.

**Comment by ankane** [comment]
Thanks @tarcieri, thinking about it more, I think the code change is probably better, since `libsodium.dll` is a clearer name/the actual name of the `dll`. What do you think about a PR for the commit above?

In the meantime, added instructions for Ubuntu Bionic to the wiki.

**Comment by tarcieri** [comment]
Sure, go ahead and open a PR and we can discuss.

**Comment by ankane** [comment]
Oddly enough, it doesn't appear to work with the `lib` prefix. It recognizes the file is there, but doesn't load it. I've updated the instructions for now.
