### ISSUE TITLE
Better example on how to do public/private key pair signing

### ISSUE THREAD

**Issue by emilebosch** [crypto-rb/rbnacl#199]
I would love to use this library, but unfortunately I am not capable of assessing exactly how pub/private signing works. Especially, generating and storing the PK, storing it and later reconstructing it. Is the seed really the only thing that needs saving?

Hope you can help me out!

**Comment by tarcieri** [comment]
It's all described here: https://github.com/crypto-rb/rbnacl/wiki/Digital-Signatures

Yes, the seed is the only thing you need to save.

**Comment by emilebosch** [comment]
I have seen and know this is a sample, but it wasn't clear to me. I don't understand how a 32bit integer can be super secure. 

This is probably what most people use this lib for. So I think adding serialisation and deserialisation to this sample would help a lot.

I can try to do it, but I need your smart brain to give me feedback! Thanks very much!

**Comment by tarcieri** [comment]
There's already a comment for serializing the public/verify key. I can add one for the signing key too.

**Comment by emilebosch** [comment]
That would be awesome. This library is basically the only one out there, and it would be awesome to nail this down properly, so that even medior devs like me can implement reasonably well security .

In my use case, I want to generate a pub/priv key pair, and distribute the pub key, so that people can verify I send the tweets out .

**Comment by tarcieri** [comment]
Updated the wiki with a note on how to serialize the signing key

**Comment by tarcieri** [comment]
Also note that if all you're doing is Ed25519 signatures, there's a separate gem for that https://github.com/crypto-rb/ed25519

**Comment by emilebosch** [comment]
This part right? https://github.com/crypto-rb/ed25519#serializing-keys. Man that's awesome. Give me your PayPal and I'll donate a couple of beers.

**Comment by tarcieri** [comment]
Haha, that's a different gem (`ed25519`) which provides the same functionality but has better documentation.

If you're just doing Ed25519 signatures it's much easier to use, since it vendors the backend code and therefore doesn't have a dependency on libsodium.

**Comment by emilebosch** [comment]
Ok good, maybe its smart to link from the Wiki article to this gem, so that people like me can find it. Still. Let me send you beers. Thanks!

**Comment by emilebosch** [comment]
Also what I am missing from the wiki is how to 

```ruby
# Serialize the signing key to a string and save it for future use
signing_key.to_s
```

get this back into a signing key

**Comment by tarcieri** [comment]
Good idea. I've done both suggestions.

**Comment by emilebosch** [comment]
Thank you <3
